### ISSUE TITLE
Default timeout override

### ISSUE THREAD

**Issue by kkingsbe** [Satak/webrequest-action#29]
I am using this to call an api endpoint on my server which triggers a redeploy. This can take quite a few seconds (approaching a minute sometimes), so most times this causes the github action to fail even though the redeploy succeeded. Would it be possible to add a way to override the default timeout?

**Comment by Satak** [comment]
Axios default timeout is `0` which is no timeout. So your job fail with GitHub action timeout which you can set in your pipeline config:

```yaml
my-job:
 runs-on:         ubuntu-latest
 timeout-minutes: 30
```
