### ISSUE TITLE
Problems with GraphQL payloads

### ISSUE THREAD

**Issue by woodie** [Satak/webrequest-action#6]
It's important not to have newlines in JSONs.
```yml
on:
  issues:
    types: [whatever]

env:
  QUERY: |
    {
      items_by_column_values(board_id: ${{ secrets.MONDAY_BOARD }},
                             column_id: \"name\",
                             column_value: \"${{ github.event.issue.title }}\") {
        id
        updates(limit: 1) {
          text_body
          creator {
            name
          }
        }
      }
    }

jobs:
  reopened-issues-monday-blurb:
    runs-on: ubuntu-latest
    steps:
      - id: query
        run: echo "::set-output name=query::$(echo $QUERY)"
        shell: bash
      - id: item_params
        uses: satak/webrequest-action@master
        with:
          url: https://api.monday.com/v2
          method: POST
          payload: '{"query":"${{ steps.query.outputs.query }}"}'
          headers: '{"Content-Type": "application/json", "Authorization": "${{ secrets.MONDAY_TOKEN }}"}'
      - id: comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            item: ${{ fromJson(steps.response.outputs.output).data.data.items_by_column_values[0].id }}
            name: ${{ fromJson(steps.response.outputs.output).data.data.items_by_column_values[0].updates[0].creator.name }}
            ${{ fromJson(steps.response.outputs.output).data.data.items_by_column_values[0].updates[0].text_body }}
```

**Comment by Satak** [comment]
Thanks for reporting, will check it out.

**Comment by woodie** [comment]
Thanks, I may have also had an error when I tried passing multiple headers.

**Comment by Satak** [comment]
> Thanks, I may have also had an error when I tried passing multiple headers.

Have you tried:
```
headers: '{"Content-Type": "application/json", "Authorization": "${{ secrets.MONDAY_TOKEN }}"}'
```

In your example you are missing couple quotes.

**Comment by woodie** [comment]
The headers are now working, but the payload still seems to have an issue.

None of the the other Github actions for web requests let me set the headers (which I need for Monday.com API Authorization), so I hope we can figure out how to properly encode GraphQL payloads with this action.

**Comment by Satak** [comment]
It seems the value after query key is just a string. Have you tried hardcoding something very simple like this?

```
'{"query":"{boards(limit:1){id name}}"}'
```

My guess is that your problem is the GraphQL string which is not correctly escaped from quotes.

**Comment by woodie** [comment]
I had some extra escapes that are now fixed in the example above. My payload is now 193 characters long, but the error is now referring to a newline at  position 228. I wonder if that's a newline in the response.
```
.github#L1
Unexpected token <newline> in JSON at position 228
```

**Comment by Satak** [comment]
> I had some extra escapes that are now fixed in the example above. My payload is now 193 characters long, but the error is now referring to a newline at position 228. I wonder if that's a newline in the response.
> 
> ```
> .github#L1
> Unexpected token <newline> in JSON at position 228
> ```

You can't have newlines in JSON. You must construct your GraphQL so that it's in single line and all needed line breaks are replaced with `\n`.

For example:

```
{items_by_column_values(board_id: ${{ secrets.MONDAY_BOARD }},column_id: \"name\",column_value: \"${{ github.event.issue.title }}\"){id\nupdates(limit: 1){text_body\ncreator {name}}}}
```

**Comment by woodie** [comment]
Turns out I had a newline at the end of my token in Github secrets. The example above is otherwise good.

**Comment by woodie** [comment]
I've got [my workflow](https://github.com/woodie/next-caltrain-pwa/blob/master/.github/workflows/reopened-issues-monday-blurb.yml) mostly working, but I need to figure out a way to construct a proper payload to send back to Github. It currently fails when links or images are added to the HTML. The plain text version has issues with newlines.

If I end up building the new payload in github-script, how do I get access to the output the the webrequest action?

**Comment by Satak** [comment]
Output is documented on the readme `${{ steps.webhook.outputs.output }}` Output is in JSON format.

**Comment by woodie** [comment]
OK, thanks! I was able to handle this by first putting everything into an environment variable.
```bash
run: |
  echo "::set-output name=body::$(echo $textbody | sed -e 's/\n/ /g' | sed -e 's/\"/\\\"/g')"
env:
  textbody: |
    ${{ fromJson(steps.response.outputs.output).data.data.items_by_column_values[0].updates[0].body }}
```

Since I'm on a Mac, so I have no idea what to expect from  ConvertFrom-Json. I will try to publish some examples using this library to work with complex payloads and process with `jq` and `sed`.

**Comment by Satak** [comment]
Seems like a good and working solution. `ConvertFrom-Json` is a Powershell command that is natively supported by GitHub actions (shell: pwsh).

```yaml
    steps:
      - name: webhook
        uses: satak/webrequest-action@master
        with:
          url: https://api.monday.com/v2
          method: POST
          payload: '{"query": "test"}'
          headers: '{"Content-Type": "application/json"}'
      - name: Output handler
        shell: pwsh
        run: |
          $output = '${{ steps.webhook.outputs.output }}' | ConvertFrom-Json
          $output
```

This issue can be now closed?
